<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Helper\" />
    <Folder Include="Mapper\" />
    <Folder Include="DTOs\" />
    <Folder Include="Services\Abstraction\" />
    <Folder Include="Services\Implementation\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sala7ly.DAL\Sala7ly.DAL.csproj" />
  </ItemGroup>

</Project>
